server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Tmss
    username: root
    password: azeem
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#  security:
#    user:
#      name: admin
#      password: adminpassword
#      roles: ADMIN

  mail:
    host: smtp.gmail.com
    port: 587
    username: mohamedazeems069@gmail.com
    password: bkiphenqcveabqeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ThisIsAVeryStrongAndSecureSecretKeyForJWTWithAtLeast256BitsLength
  expiration: 86400000

logging:
  level:
    com.travelmanagementservice: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
